In [2]:
import numpy as npo
import pandas as pd
import os

In [4]:
DIR = os.getcwd() + "/cornell movie-dialogs corpus"
DIR

'/Users/andreacutrera/Desktop/cornell movie-dialogs corpus'

In [5]:
os.listdir(DIR)

['.DS_Store',
 'raw_script_urls.txt',
 'README.txt',
 'movie_titles_metadata.txt',
 'movie_characters_metadata.txt',
 'movie_lines.txt',
 'chameleons.pdf',
 'movie_conversations.txt']

In [ ]:
from convokit import Corpus, download

In [12]:
corpus = Corpus(filename=download("movie-corpus"))

Downloading movie-corpus to /Users/andreacutrera/.convokit/downloads/movie-corpus
Downloading movie-corpus from http://zissou.infosci.cornell.edu/convokit/datasets/movie-corpus/movie-corpus.zip (40.9MB)... Done

In [13]:
corpus.print_summary_stats()

Number of Speakers: 9035
Number of Utterances: 304713
Number of Conversations: 83097

In [15]:
utt = corpus.random_utterance()
print(utt)

Utterance(id: 'L662763', conversation_id: L662763, reply-to: None, speaker: Speaker(id: u8974, vectors: [], meta: {'character_name': 'ZUKOVSKY', 'movie_idx': 'm611', 'movie_name': 'the world is not enough', 'gender': 'm', 'credit_pos': '5'}), timestamp: None, text: 'That too. Everyone does what they can to survive.', vectors: [], meta: {'movie_id': 'm611', 'parsed': [{'rt': 1, 'toks': [{'tok': 'That', 'tag': 'DT', 'dep': 'advmod', 'up': 1, 'dn': []}, {'tok': 'too', 'tag': 'RB', 'dep': 'ROOT', 'dn': [0, 2]}, {'tok': '.', 'tag': '.', 'dep': 'punct', 'up': 1, 'dn': []}]}, {'rt': 1, 'toks': [{'tok': 'Everyone', 'tag': 'NN', 'dep': 'nsubj', 'up': 1, 'dn': []}, {'tok': 'does', 'tag': 'VBZ', 'dep': 'ROOT', 'dn': [0, 4, 7]}, {'tok': 'what', 'tag': 'WP', 'dep': 'dobj', 'up': 4, 'dn': []}, {'tok': 'they', 'tag': 'PRP', 'dep': 'nsubj', 'up': 4, 'dn': []}, {'tok': 'can', 'tag': 'MD', 'dep': 'ccomp', 'up': 1, 'dn': [2, 3, 6]}, {'tok': 'to', 'tag': 'TO', 'dep': 'aux', 'up': 6, 'dn': []}, {'tok': 'survive', 'tag': 'VB', 'dep': 'advcl', 'up': 4, 'dn': [5]}, {'tok': '.', 'tag': '.', 'dep': 'punct', 'up': 1, 'dn': []}]}]})

In [16]:
# primary data fields
print("ID:", utt.id, "\n")

print("Reply_to:", utt.reply_to, "\n")

print("Timestamp:", utt.timestamp, "\n")

print("Text:", utt.text, "\n")

print("Conversation ID:", utt.conversation_id, "\n")

print("Speaker ID:", utt.speaker.id)

ID: L662763

Reply_to: None

Timestamp: None

Text: That too. Everyone does what they can to survive.

Conversation ID: L662763

Speaker ID: u8974

In [17]:
utt.meta

{'movie_id': 'm611',
 'parsed': [{'rt': 1,
   'toks': [{'tok': 'That', 'tag': 'DT', 'dep': 'advmod', 'up': 1, 'dn': []},
    {'tok': 'too', 'tag': 'RB', 'dep': 'ROOT', 'dn': [0, 2]},
    {'tok': '.', 'tag': '.', 'dep': 'punct', 'up': 1, 'dn': []}]},
  {'rt': 1,
   'toks': [{'tok': 'Everyone',
     'tag': 'NN',
     'dep': 'nsubj',
     'up': 1,
     'dn': []},
    {'tok': 'does', 'tag': 'VBZ', 'dep': 'ROOT', 'dn': [0, 4, 7]},
    {'tok': 'what', 'tag': 'WP', 'dep': 'dobj', 'up': 4, 'dn': []},
    {'tok': 'they', 'tag': 'PRP', 'dep': 'nsubj', 'up': 4, 'dn': []},
    {'tok': 'can', 'tag': 'MD', 'dep': 'ccomp', 'up': 1, 'dn': [2, 3, 6]},
    {'tok': 'to', 'tag': 'TO', 'dep': 'aux', 'up': 6, 'dn': []},
    {'tok': 'survive', 'tag': 'VB', 'dep': 'advcl', 'up': 4, 'dn': [5]},
    {'tok': '.', 'tag': '.', 'dep': 'punct', 'up': 1, 'dn': []}]}]}

In [29]:
speakers = corpus.get_speakers_dataframe()
speakers.head()

,vectors,meta.character_name,meta.movie_idx,meta.movie_name,meta.gender,meta.credit_pos
id,,,,,,
u0,[],BIANCA,m0,10 things i hate about you,f,4
u2,[],CAMERON,m0,10 things i hate about you,m,3
u3,[],CHASTITY,m0,10 things i hate about you,?,?
u4,[],JOEY,m0,10 things i hate about you,m,6
u5,[],KAT,m0,10 things i hate about you,f,2

In [31]:
speakers['meta.movie_name'].unique()

array(['10 things i hate about you', '1492: conquest of paradise',
       '15 minutes', '2001: a space odyssey', '48 hrs.',
       'the fifth element', '8mm',
       'a nightmare on elm street 4: the dream master',
       'a nightmare on elm street: the dream child',
       'the atomic submarine', 'affliction', 'air force one',
       'airplane ii: the sequel', 'airplane!', 'alien nation', 'aliens',
       'amadeus', 'an american werewolf in london', 'american madness',
       'american outlaws', 'american psycho', 'antitrust',
       'austin powers: international man of mystery', 'the avengers',
       'bachelor party', 'backdraft', 'bad lieutenant', 'bamboozled',
       'barry lyndon', 'basic', 'big fish', 'birthday girl',
       'black snake moan', 'black rain', 'blade runner',
       'blast from the past', 'blue velvet', 'the boondock saints',
       'bottle rocket', 'the bourne supremacy', 'braveheart',
       'the butterfly effect', 'casablanca', 'cast away',
       'the cider house rules', 'confidence', 'croupier', 'dark star',
       'dark angel', 'detroit rock city', 'donnie darko',
       'drop dead gorgeous', 'duck soup', 'the elephant man',
       'erik the viking', 'eternal sunshine of the spotless mind',
       'even cowgirls get the blues', 'event horizon', 'fantastic four',
       'fast times at ridgemont high', 'fear and loathing in las vegas',
       'feast', 'frances', 'frankenstein', 'friday the 13th',
       'from dusk till dawn', 'g.i. jane', 'godzilla', 'galaxy quest',
       'george washington', 'get shorty', 'ghost ship', 'ghost world',
       'the ghost and the darkness', 'ghostbusters ii', 'ghostbusters',
       'gladiator', 'the graduate', 'grand hotel', 'the grifters',
       'halloween h20: 20 years later',
       'halloween: the curse of michael myers',
       'happy birthday, wanda june', 'hardcore', 'harold and maude',
       'hellbound: hellraiser ii', 'hellboy', 'hellraiser',
       'high fidelity', 'highlander', 'his girl friday', 'hope and glory',
       'house of 1000 corpses', 'human nature', 'the hustler',
       'i am legend', 'invaders from mars', 'independence day',
       'indiana jones and the last crusade',
       'indiana jones and the temple of doom', 'innerspace',
       'the insider', 'intolerable cruelty', 'it happened one night',
       'jfk', 'jackie brown', "jacob's ladder", 'jason x', 'jaws', 'juno',
       'kalifornia', 'kids', 'knight moves', 'krull', 'lon',
       'labor of love', 'leaving las vegas', 'legally blonde', 'legend',
       'life as a house', 'the life of david gale', 'little nicky',
       "logan's run", 'lost highway', 'lost horizon', 'men in black',
       'minority report', 'made', 'malcolm x', 'man on fire', 'marty',
       'mash', 'meet john doe', 'metro', 'metropolis',
       'mighty morphin power rangers', 'mobsters', 'monkeybone',
       "my mother dreams the satan's disciples in new york",
       'mr. smith goes to washington', 'mr. deeds goes to town',
       'mumford', 'the mummy', 'mystery men', 'napoleon', 'next friday',
       'nick of time', 'the night of the hunter',
       'a nightmare on elm street', 'ninotchka', 'nixon',
       'no country for old men', 'nurse betty',
       'o brother, where art thou?', 'an officer and a gentleman',
       'panic room', 'panther', 'the patriot', 'pet sematary',
       'pirates of the caribbean', 'plastic man', 'platinum blonde',
       'pleasantville', 'punch-drunk love', 'quills', 'rko 281',
       'raging bull', 'rear window', 'rebel without a cause',
       'reindeer games', 'reservoir dogs', 'roughshod', 'scary movie 2',
       'serial mom', 'the seventh victim', 'sex, lies, and videotape',
       'shivers', 'shock treatment', 'sideways', 'signs', 'silverado',
       'simone', 'the sixth sense', 'slash', 'slither',
       'smokey and the bandit', "smokin' aces", 'solaris',
       'someone to watch over me', 'spider-man', 'stalag 17',
       'star trek: generations', 'star trek iii: the search for spock',
       'star trek: the wrath of khan', 'star trek iv: the voyage home',
       'star trek: insurrection', 'star trek: first contact',
       'star trek vi: the undiscovered country', 'star trek: nemesis',
       'starman', 'strange days', 'suspect zero', 'swingers',
       'the godfather', 'the talented mr. ripley', 'taxi driver',
       'the rock', 'the majestic', 'the birds', 'the body snatcher',
       'the crow: salvation', 'the day the earth stood still',
       'the lost boys', 'the thing', 'the time machine', 'the jacket',
       'thelma & louise', "there's something about mary", 'thirteen days',
       'thunderheart', 'top gun', 'total recall', 'tremors',
       'true believer', 'twin peaks: fire walk with me', 'the verdict',
       'the war of the worlds', 'new nightmare', 'white squall',
       'wild at heart', 'wonder boys', 'the woodsman', 'the abyss',
       "l'avventura", 'agnes of god', "a hard day's night", 'alien',
       'alien vs. predator', 'all about eve', "all the president's men",
       'american pie', 'an american werewolf in paris', 'anastasia',
       'annie hall', 'the anniversary party', 'antz', 'the apartment',
       'apocalypse now', 'arctic blue', 'as good as it gets', 'assassins',
       'asylum', 'a walk to remember', 'back to the future', 'badlands',
       'the adventures of buckaroo banzai across the 8th dimension',
       'barton fink', 'basic instinct', 'basquiat', 'batman returns',
       'batman and robin', 'batman forever', 'batman', 'bean',
       'beavis and butt-head do america', 'beetle juice', 'being there',
       'being john malkovich', 'beloved', 'the big lebowski',
       'the black dahlia', 'blade ii', 'blade',
       'book of shadows: blair witch 2', 'blood simple.', 'bloodmoon',
       'blow', 'la battaglia di algeri', 'body of evidence',
       'the bridges of madison county', 'bones', 'bound',
       'the bourne identity', 'brazil', 'bringing out the dead',
       'broadcast news', 'a bucket of blood', 'buffy the vampire slayer',
       'bull durham', 'casino', 'catwoman', 'cellular', 'the crying game',
       'charade', 'cherry falls', 'chill factor', 'chinatown',
       'nuovo cinema paradiso', 'citizen kane', 'clerks.', 'cliffhanger',
       'a clockwork orange', 'collateral', 'conspiracy theory', 'contact',
       'cool hand luke', 'copycat', 'crash', 'crazy love', 'crime spree',
       'crouching tiger, hidden dragon', 'the crow', 'cruel intentions',
       'the curse of the cat people', 'the curse', 'dark city', 'dave',
       'day of the dead', 'dead poets society', 'deep rising',
       'the deer hunter', 'demolition man',
       'the devil and daniel webster', 'die hard', 'dog day afternoon',
       'domino', 'do the right thing',
       'dumb and dumberer: when harry met lloyd', 'dune', 'ed wood',
       'edtv', 'election', 'l.a. confidential', 'enemy of the state',
       'the english patient', 'entrapment', 'erin brockovich',
       'star wars: the empire strikes back',
       'escape from the planet of the apes', 'escape from l.a.',
       'excalibur', 'the exorcist', 'the fabulous baker boys', 'face/off',
       'the family man', 'the fantastic four', 'fantastic voyage',
       'fargo', 'fight club', 'final destination 2', 'final destination',
       'rambo: first blood part ii', 'the fisher king',
       'five easy pieces', 'five feet high and rising', 'fletch',
       'the adventures of ford fairlane', 'the french connection',
       'frequency', 'friday the 13th part iii',
       'jason lives: friday the 13th part vi',
       'jason goes to hell: the final friday',
       'friday the 13th part viii: jason takes manhattan', 'game 6',
       'gandhi', 'gattaca', 'the getaway', 'get carter',
       'glengarry glen ross', 'the godfather: part ii',
       'gods and monsters', 'gone in sixty seconds', 'goodfellas',
       'good will hunting', 'the grapes of wrath', 'grosse pointe blank',
       'the horse whisperer', 'hackers',
       'halloween 4: the return of michael myers', 'halloween',
       'hannah and her sisters', 'hannibal', 'happy campers', 'heathers',
       'heavenly creatures', 'hellraiser: hellseeker', 'hero',
       'hider in the house', 'highlander iii: the sorcerer', 'hostage',
       'hotel rwanda', 'house on haunted hill', 'house of the damned',
       'hellraiser iii: hell on earth', 'hudson hawk',
       'the hudsucker proxy', 'i walked with a zombie', 'the ice storm',
       'insomnia', 'interview with the vampire: the vampire chronicles',
       'i still know what you did last summer', 'isle of the dead',
       "it's a wonderful life", 'jaws 2', 'jaws 3-d', 'jaws: the revenge',
       'the jazz singer', 'jennifer eight', 'jerry maguire',
       'jurassic park iii', 'the lost world: jurassic park',
       'jurassic park', 'freddy vs. jason', 'kafka', 'king kong', 'klute',
       'kramer vs. kramer', 'kundun', 'lake placid',
       'the silence of the lambs', 'last of the mohicans', 'leviathan',
       'lock, stock and two smoking barrels', 'lone star',
       'lord of illusions', 'lost in translation', 'lost souls',
       'love & basketball', 'magnolia', 'the man in the iron mask',
       'manhunt', 'manhunter', 'man on the moon', 'the matrix',
       'halloween iii: season of the witch', 'meet joe black', 'memento',
       'miami vice', 'midnight cowboy', 'midnight express', 'mimic',
       'misery', 'mission: impossible ii', 'mission: impossible',
       'moonstruck', 'monty python and the holy grail', 'mrs brown',
       'arcade', 'mulholland dr.', '"murderland"', 'my girl 2', 'my girl',
       "my best friend's wedding", 'nashville', 'natural born killers',
       'nothing but a man', 'the negotiator', 'neuromancer',
       'never been kissed', 'the nightmare before christmas',
       "a nightmare on elm street part 2: freddy's revenge",
       'a nightmare on elm street 3: dream warriors', 'notting hill',
       "one flew over the cuckoo's nest", 'only you', 'on the waterfront',
       'orgy of the dead', 'out of sight', 'pearl harbor',
       'peggy sue got married', 'pet sematary ii', 'philadelphia',
       'pitch black', 'planet of the apes', 'platoon', 'playback',
       "the ploughman's lunch", 'point break', 'predator', 'pretty woman',
       'the princess bride', 'the producers', 'psycho', 'maniac',
       'vampyr', 'mystery of the wax museum', 'quantum project',
       'rambling rose', 'red white black & blue',
       'star wars: episode vi - return of the jedi',
       'the rocky horror picture show', 'rocky',
       'who framed roger rabbit', 'romeo and juliet', 'ronin', 'route 9',
       'rush hour 2', 'rush hour', 'runaway bride',
       'sleepless in seattle', 'salt of the earth', 'the salton sea',
       'saving private ryan', 'say anything...', "schindler's list",
       'scream 2', 'scream 3', 'scream', 'seven', 'the searchers',
       'seven days to live', 'shakespeare in love', 'shallow grave',
       'shampoo', 'the shining', 'silver bullet', 'sister act',
       'sleepy hollow', 'sling blade', 'smoke', 'snow falling on cedars',
       'soldier', 'some like it hot', 'the wedding date', 'sounder',
       'south park: bigger longer & uncut', 'spacejacked', 'spare me',
       'sphere', 'star wars', 'starship troopers',
       'star trek: the motion picture', 'state and main', 'stepmom',
       'storytelling', 'stranglehold',
       'dr. strangelove or: how i learned to stop worrying and love the bomb',
       'suburbia', 'sugar & spice', 'sunset blvd.', 'supergirl',
       'superman iii', 'superman ii', 'superman iv: the quest for peace',
       'superman', 'the sweet hereafter', 'sweet smell of success',
       'terminator 2: judgment day', 'taking sides', 'the terminator',
       'the game', 'the haunting', 'the limey',
       "the man who wasn't there", 'the relic', 'the truman show',
       'the x files', 'the cell', 'the third man', 'the beach',
       'the believer', 'le grand bleu', 'the hebrew hammer',
       'the leopard man', 'the lost son', 'the messenger', 'the pianist',
       'the piano', 'the sting', 'the thin man', 'three kings',
       'thx 1138', 'ticker', 'trouble in paradise', 'titanic',
       'transatlantic merry-go-round', 'tombstone', 'tomorrow never dies',
       'to sleep with anger', 'toy story', 'the magic toyshop', 'traffic',
       'trainspotting', 'star trek v: the final frontier', 'tron',
       'true lies', 'true romance', 'twelve monkeys', 'u-turn', 'u turn',
       'unbreakable', 'unforgiven', 'the usual suspects', 'verdict',
       'vertigo', 'very bad things', 'viridiana', 'virtuosity',
       'wag the dog', 'wall street', 'waxwork', 'what lies beneath',
       'what women want', 'the witching hour', 'white angel',
       "who's your daddy?", 'wild things', 'wild wild west', 'willow',
       'witness', 'the wizard of oz', 'the world is not enough',
       'watchmen', 'xxx', 'x-men', 'young frankenstein', 'zulu dawn'],
      dtype=object)

## We select the film:          
#                                   "The Godfather"
by Mario Puzo and Francis Ford Coppola
Third Draft
March 29, 1971

## Don Vito Corleone

In [39]:
from IPython.display import Image
Image(url='https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg', width=200)

## Tom Hagen

In [105]:
Image(url='https://upload.wikimedia.org/wikipedia/en/6/67/Tom_Hagen.jpg', width=200)

## Michael Corleone

In [106]:
Image(url='https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Michaelcoreleone.jpg/220px-Michaelcoreleone.jpg', width=200)

## Peter Clemenza

In [107]:
Image(url='https://upload.wikimedia.org/wikipedia/en/2/29/Peter_Clemenza.png', width=200)

## Sonny Corleone

In [108]:
Image(url='https://upload.wikimedia.org/wikipedia/en/9/9d/Santino_corleone_2.jpg', width=200)

In [48]:
# variables to select our film and the main characters

movie_name = "the godfather"     # title of the film
movie_id = "m203"                # identifier of the film

tom_hagen = "HAGEN"              # the most loyal to the family - the counselor of don corleone - the lawyer
don_corleone = "DON CORLEONE"    # the main character, the godfather
michael = "MICHAEL"              # the quiet son of don corleone, the successor of the family
clemenza = "CLEMENZA"            # one of the main henchmans 
sonny = "SONNY"                  # the most exhuberant son of the godfather which would be killed by rival family

tom_hagen_id = "u3102"
don_corleone_id = "u3098"
michael_id = "u3105"
clemenza_id = "u3096"
sonny_id = "u3112"

In [49]:
characters = speakers[speakers['meta.movie_name'] == movie_name]
characters

,vectors,meta.character_name,meta.movie_idx,meta.movie_name,meta.gender,meta.credit_pos
id,,,,,,
u3102,[],HAGEN,m203,the godfather,m,5
u3094,[],BONASERA,m203,the godfather,?,?
u3098,[],DON CORLEONE,m203,the godfather,m,?
u3105,[],MICHAEL,m203,the godfather,m,2
u3095,[],CARLO,m203,the godfather,?,?
u3097,[],CONNIE,m203,the godfather,?,?
u3096,[],CLEMENZA,m203,the godfather,?,?
u3112,[],SONNY,m203,the godfather,m,3
u3109,[],PAULIE,m203,the godfather,?,?
u3111,[],SOLLOZZO,m203,the godfather,?,?
u3103,[],JOHNNY,m203,the godfather,?,?
u3107,[],NAZORINE,m203,the godfather,?,?
u3099,[],DON TOMMASSINO,m203,the godfather,?,?
u3100,[],FABRIZZIO,m203,the godfather,?,?
u3114,[],VITELLI,m203,the godfather,?,?
u3101,[],FREDO,m203,the godfather,?,?
u3104,[],KAY,m203,the godfather,f,10
u3116,[],WOLTZ,m203,the godfather,?,?
u3108,[],NURSE,m203,the godfather,?,?
u3110,[],PRIEST,m203,the godfather,?,?
u3113,[],TESSIO,m203,the godfather,?,?
u3106,[],MOE,m203,the godfather,?,?
u3115,[],VOICE,m203,the godfather,?,?

In [53]:
characters['meta.character_name'].values

array(['HAGEN', 'BONASERA', 'DON CORLEONE', 'MICHAEL', 'CARLO', 'CONNIE',
       'CLEMENZA', 'SONNY', 'PAULIE', 'SOLLOZZO', 'JOHNNY', 'NAZORINE',
       'DON TOMMASSINO', 'FABRIZZIO', 'VITELLI', 'FREDO', 'KAY', 'WOLTZ',
       'NURSE', 'PRIEST', 'TESSIO', 'MOE', 'VOICE'], dtype=object)

In [54]:
characters[characters.index == tom_hagen_id]

,vectors,meta.character_name,meta.movie_idx,meta.movie_name,meta.gender,meta.credit_pos
id,,,,,,
u3102,[],HAGEN,m203,the godfather,m,5

In [56]:
conversations = corpus.get_conversations_dataframe()
conversations.head()

,vectors,meta.movie_idx,meta.movie_name,meta.release_year,meta.rating,meta.votes,meta.genre
id,,,,,,,
L1044,[],m0,10 things i hate about you,1999,6.90,62847,"['comedy', 'romance']"
L984,[],m0,10 things i hate about you,1999,6.90,62847,"['comedy', 'romance']"
L924,[],m0,10 things i hate about you,1999,6.90,62847,"['comedy', 'romance']"
L870,[],m0,10 things i hate about you,1999,6.90,62847,"['comedy', 'romance']"
L866,[],m0,10 things i hate about you,1999,6.90,62847,"['comedy', 'romance']"

In [58]:
conversations = conversations[conversations['meta.movie_name'] == movie_name]

In [74]:
conversations

,vectors,meta.movie_idx,meta.movie_name,meta.release_year,meta.rating,meta.votes,meta.genre
id,,,,,,,
L593443,[],m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']"
L593422,[],m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']"
L593420,[],m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']"
L593431,[],m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']"
L592861,[],m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']"
...,...,...,...,...,...,...,...
L593594,[],m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']"
L593584,[],m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']"
L593582,[],m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']"
L593578,[],m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']"
L593077,[],m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']"

In [73]:
conversations['meta.genre'].unique()

array(["['crime', 'drama', 'thriller']"], dtype=object)

In [76]:
conversations.index # what we need to filter out the utterances of the film selected

Index(['L593443', 'L593422', 'L593420', 'L593431', 'L592861', 'L592858',
       'L592852', 'L592849', 'L593722', 'L593719',
       ...
       'L593686', 'L593675', 'L593629', 'L593615', 'L593596', 'L593594',
       'L593584', 'L593582', 'L593578', 'L593077'],
      dtype='object', name='id', length=147)

In [77]:
utterances = corpus.get_utterances_dataframe()
utterances.head()

,timestamp,text,speaker,reply_to,conversation_id,meta.movie_id,meta.parsed,vectors
id,,,,,,,,
L1045,None,They do not!,u0,L1044,L1044,m0,"[{'rt': 1, 'toks': [{'tok': 'They', 'tag': 'PR...",[]
L1044,None,They do to!,u2,None,L1044,m0,"[{'rt': 1, 'toks': [{'tok': 'They', 'tag': 'PR...",[]
L985,None,I hope so.,u0,L984,L984,m0,"[{'rt': 1, 'toks': [{'tok': 'I', 'tag': 'PRP',...",[]
L984,None,She okay?,u2,None,L984,m0,"[{'rt': 1, 'toks': [{'tok': 'She', 'tag': 'PRP...",[]
L925,None,Let's go.,u0,L924,L924,m0,"[{'rt': 0, 'toks': [{'tok': 'Let', 'tag': 'VB'...",[]

In [85]:
utterances = utterances[(utterances['meta.movie_id'] == movie_id) &
                        ((utterances['speaker'] == tom_hagen_id) |
                         (utterances['speaker'] == don_corleone_id) |
                         (utterances['speaker'] == michael_id) |
                         (utterances['speaker'] == clemenza_id) |
                         (utterances['speaker'] == sonny_id))]
utterances

,timestamp,text,speaker,reply_to,conversation_id,meta.movie_id,meta.parsed,vectors
id,,,,,,,,
L593445,None,You owe the Don a service. He has no doubt th...,u3102,L593444,L593443,m203,"[{'rt': 1, 'toks': [{'tok': 'You', 'tag': 'PRP...",[]
L593443,None,This is Tom Hagen; I'm calling for Don Corleon...,u3102,None,L593443,m203,"[{'rt': 7, 'toks': [{'tok': 'This', 'tag': 'DT...",[]
L593425,None,Yes.,u3102,L593424,L593422,m203,"[{'rt': 0, 'toks': [{'tok': 'Yes', 'tag': 'UH'...",[]
L593423,None,Good. He never doubted you.,u3102,L593422,L593422,m203,"[{'rt': 0, 'toks': [{'tok': 'Good', 'tag': 'JJ...",[]
L593421,None,"You owe the Don a service. In one hour, not b...",u3102,L593420,L593420,m203,"[{'rt': 1, 'toks': [{'tok': 'You', 'tag': 'PRP...",[]
...,...,...,...,...,...,...,...,...
L593579,None,Thanks.,u3105,L593578,L593578,m203,"[{'rt': 0, 'toks': [{'tok': 'Thanks', 'tag': '...",[]
L593083,None,Find out anything you can...you got a Grand co...,u3112,L593082,L593077,m203,"[{'rt': 0, 'toks': [{'tok': 'Find', 'tag': 'VB...",[]
L593081,None,Is he alive?,u3112,L593080,L593077,m203,"[{'rt': 0, 'toks': [{'tok': 'Is', 'tag': 'VBZ'...",[]
L593079,None,I think so. Detective squad?,u3112,L593078,L593077,m203,"[{'rt': 1, 'toks': [{'tok': 'I', 'tag': 'PRP',...",[]
L593077,None,Yeah.,u3112,None,L593077,m203,"[{'rt': 0, 'toks': [{'tok': 'Yeah', 'tag': 'UH...",[]

In [86]:
utterances['speaker'].unique()

array(['u3102', 'u3098', 'u3105', 'u3096', 'u3112'], dtype=object)

In [87]:
print(tom_hagen_id, don_corleone_id, michael_id, clemenza_id, sonny_id)

u3102 u3098 u3105 u3096 u3112

In [111]:
lengths = []
for i in range(len(utterances)):
    lengths.append(len(utterances['text'][i].split()))
    
lengths

[15,
 12,
 1,
 5,
 41,
 27,
 22,
 6,
 38,
 90,
 6,
 5,
 6,
 5,
 38,
 14,
 79,
 32,
 25,
 6,
 9,
 8,
 3,
 30,
 5,
 28,
 4,
 5,
 11,
 5,
 48,
 1,
 15,
 5,
 12,
 21,
 26,
 12,
 9,
 11,
 10,
 1,
 5,
 2,
 13,
 45,
 12,
 14,
 59,
 5,
 28,
 6,
 13,
 12,
 1,
 7,
 20,
 1,
 38,
 22,
 9,
 5,
 12,
 8,
 35,
 6,
 14,
 19,
 4,
 61,
 23,
 6,
 1,
 3,
 15,
 16,
 5,
 1,
 6,
 19,
 36,
 20,
 4,
 19,
 16,
 20,
 8,
 9,
 13,
 5,
 15,
 40,
 2,
 4,
 34,
 4,
 7,
 25,
 8,
 6,
 3,
 1,
 1,
 7,
 21,
 1,
 6,
 94,
 3,
 7,
 5,
 9,
 6,
 12,
 64,
 9,
 25,
 7,
 7,
 31,
 4,
 12,
 11,
 1,
 8,
 15,
 5,
 8,
 9,
 6,
 4,
 2,
 2,
 4,
 7,
 11,
 16,
 8,
 9,
 3,
 10,
 5,
 7,
 6,
 27,
 1,
 2,
 9,
 2,
 14,
 11,
 1,
 1,
 6,
 8,
 20,
 8,
 4,
 8,
 4,
 5,
 1,
 4,
 9,
 39,
 10,
 33,
 25,
 29,
 28,
 9,
 5,
 4,
 21,
 4,
 9,
 87,
 18,
 11,
 6,
 19,
 5,
 10,
 45,
 8,
 13,
 10,
 26,
 5,
 8,
 18,
 55,
 3,
 9,
 12,
 8,
 60,
 13,
 19,
 11,
 10,
 8,
 12,
 22,
 4,
 3,
 10,
 2,
 32,
 6,
 13,
 8,
 10,
 10,
 9,
 2,
 14,
 14,
 13,
 6,
 9,
 6,
 20,
 6,
 12,
 39,
 14,
 5,
 6,
 36,
 28,
 21,
 10,
 18,
 3,
 1,
 16,
 7,
 2,
 13,
 15,
 3,
 6,
 2,
 3,
 7,
 11,
 16,
 1,
 11,
 8,
 17,
 16,
 6,
 2,
 1,
 4,
 3,
 2,
 12,
 4,
 1,
 8,
 13,
 13,
 17,
 7,
 10,
 1,
 24,
 4,
 8,
 7,
 15,
 7,
 8,
 6,
 35,
 37,
 12,
 3,
 5,
 10,
 15,
 23,
 6,
 9,
 37,
 27,
 6,
 15,
 3,
 11,
 23,
 3,
 20,
 14,
 89,
 3,
 3,
 24,
 23,
 3,
 4,
 3,
 28,
 28,
 19,
 3,
 3,
 4,
 9,
 7,
 5,
 33,
 8,
 42,
 6,
 7,
 10,
 36,
 5,
 9,
 6,
 7,
 1,
 11,
 1,
 6,
 20,
 5,
 26,
 2,
 15,
 10,
 17,
 5,
 12,
 6,
 4,
 4,
 3,
 4,
 10,
 2,
 3,
 13,
 5,
 12,
 26,
 2,
 9,
 12,
 9,
 1,
 9,
 3,
 5,
 1]

In [96]:
# the longest one, all the others have less than 50 words
utterances['text'][9]

"You never think to protect yourself with real friends.  You think it's enough to be an American.  All right, the Police protects you, there are Courts of Law, so you don't need a friend like me. But now you come to me and say Don Corleone, you must give me justice. And you don't ask in respect or friendship.  And you don't think to call me Godfather; instead you come to my house on the day my daughter is to be married and you ask me to do murder...for money."

In [98]:
code_to_names = {tom_hagen_id: tom_hagen,
                 don_corleone_id: don_corleone,
                 michael_id: michael,
                 clemenza_id: clemenza,
                 sonny_id: sonny}
code_to_names

{'u3102': 'HAGEN',
 'u3098': 'DON CORLEONE',
 'u3105': 'MICHAEL',
 'u3096': 'CLEMENZA',
 'u3112': 'SONNY'}

In [99]:
utterances["character"] = utterances["speaker"].map(code_to_names)
utterances

/var/folders/24/nqjd68556n7_t8xcfyl1lvpc0000gn/T/ipykernel_43345/1889326420.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  utterances["character"] = utterances["speaker"].map(code_to_names)

,timestamp,text,speaker,reply_to,conversation_id,meta.movie_id,meta.parsed,vectors,character
id,,,,,,,,,
L593445,None,You owe the Don a service. He has no doubt th...,u3102,L593444,L593443,m203,"[{'rt': 1, 'toks': [{'tok': 'You', 'tag': 'PRP...",[],HAGEN
L593443,None,This is Tom Hagen; I'm calling for Don Corleon...,u3102,None,L593443,m203,"[{'rt': 7, 'toks': [{'tok': 'This', 'tag': 'DT...",[],HAGEN
L593425,None,Yes.,u3102,L593424,L593422,m203,"[{'rt': 0, 'toks': [{'tok': 'Yes', 'tag': 'UH'...",[],HAGEN
L593423,None,Good. He never doubted you.,u3102,L593422,L593422,m203,"[{'rt': 0, 'toks': [{'tok': 'Good', 'tag': 'JJ...",[],HAGEN
L593421,None,"You owe the Don a service. In one hour, not b...",u3102,L593420,L593420,m203,"[{'rt': 1, 'toks': [{'tok': 'You', 'tag': 'PRP...",[],HAGEN
...,...,...,...,...,...,...,...,...,...
L593579,None,Thanks.,u3105,L593578,L593578,m203,"[{'rt': 0, 'toks': [{'tok': 'Thanks', 'tag': '...",[],MICHAEL
L593083,None,Find out anything you can...you got a Grand co...,u3112,L593082,L593077,m203,"[{'rt': 0, 'toks': [{'tok': 'Find', 'tag': 'VB...",[],SONNY
L593081,None,Is he alive?,u3112,L593080,L593077,m203,"[{'rt': 0, 'toks': [{'tok': 'Is', 'tag': 'VBZ'...",[],SONNY
L593079,None,I think so. Detective squad?,u3112,L593078,L593077,m203,"[{'rt': 1, 'toks': [{'tok': 'I', 'tag': 'PRP',...",[],SONNY
L593077,None,Yeah.,u3112,None,L593077,m203,"[{'rt': 0, 'toks': [{'tok': 'Yeah', 'tag': 'UH...",[],SONNY

In [102]:
utterances = utterances[['text', 'character', 'conversation_id', 'reply_to']]
utterances

,text,character,conversation_id,reply_to
id,,,,
L593445,You owe the Don a service. He has no doubt th...,HAGEN,L593443,L593444
L593443,This is Tom Hagen; I'm calling for Don Corleon...,HAGEN,L593443,None
L593425,Yes.,HAGEN,L593422,L593424
L593423,Good. He never doubted you.,HAGEN,L593422,L593422
L593421,"You owe the Don a service. In one hour, not b...",HAGEN,L593420,L593420
...,...,...,...,...
L593579,Thanks.,MICHAEL,L593578,L593578
L593083,Find out anything you can...you got a Grand co...,SONNY,L593077,L593082
L593081,Is he alive?,SONNY,L593077,L593080
L593079,I think so. Detective squad?,SONNY,L593077,L593078
L593077,Yeah.,SONNY,L593077,None

In [104]:
utterances.to_csv("the_godfather_utterances.csv")